# Generated by Django 2.2.3 on 2019-07-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_bitsian',
            field=models.BooleanField(default=True),
        ),
    ]
