# Generated by Django 2.2.3 on 2019-07-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmp', '0002_profile_new_bitsian'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hostel',
            field=models.CharField(choices=[('RM', 'Ram Bhawan'), ('BUDH', 'Budh Bhawan'), ('SR-A', 'Srinivasa Ramanujan A'), ('SR-B', 'Srinivasa Ramanujan B'), ('SR-C', 'Srinivasa Ramanujan C'), ('SR-D', 'Srinivasa Ramanujan D'), ('KR', 'Krishna Bhawan'), ('GN', 'Gandhi Bhawan'), ('SK', 'Shankar Bhawan'), ('VY', 'Vyas Bhawan'), ('VK', 'Vishwakarma Bhawan'), ('BG', 'Bhagirath Bhawan'), ('RP', 'Rana Pratap Bhawan'), ('AK', 'Ashok Bhawan'), ('MV-A', 'Malviya-A Bhawan'), ('MV-B', 'Malviya-B Bhawan'), ('MV-C', 'Malviya-C Bhawan'), ('MR-1', 'Meera Bhawan Block-1'), ('MR-2', 'Meera Bhawan Block-2'), ('MR-3', 'Meera Bhawan Block-3'), ('MR-4', 'Meera Bhawan Block-4'), ('MR-5', 'Meera Bhawan Block-5'), ('MR-6', 'Meera Bhawan Block-6'), ('MR-7', 'Meera Bhawan Block-7'), ('MR-8', 'Meera Bhawan Block-8'), ('MR-9', 'Meera Bhawan Block-9'), ('MR-10', 'Meera Bhawan Block-10')], default='RM', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='room_no',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='bits_id',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dual_branch',
            field=models.CharField(choices=[('B1', 'M.Sc. Biological Sciences'), ('B2', 'M.Sc. Chemistry'), ('B3', 'M.Sc. Economics'), ('B4', 'M.Sc. Mathematics'), ('B5', 'M.Sc. Physics')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='single_branch',
            field=models.CharField(choices=[('A1', 'B.E. Chemical'), ('A2', 'B.E. Civil'), ('A7', 'B.E. Computer Science'), ('A3', 'B.E. Electrical & Electronics'), ('A8', 'B.E. Electronics & Instrumentation'), ('A4', 'B.E. Mechanical'), ('AB', 'B.E. Manufacturing'), ('A5', 'B.Pharm.')], max_length=100),
        ),
    ]
