# Generated by Django 2.2.3 on 2019-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmp', '0003_auto_20190717_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='new_bitsian',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
