# Generated by Django 2.2.3 on 2019-07-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmp', '0004_auto_20190717_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='M', max_length=6),
            preserve_default=False,
        ),
    ]
