# Generated by Django 2.2.3 on 2019-07-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmp', '0005_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='room_no',
            field=models.IntegerField(null=True),
        ),
    ]
