# Generated by Django 2.2.3 on 2019-07-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmp', '0006_auto_20190717_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bits_id',
            field=models.CharField(max_length=13),
        ),
    ]
