# Generated by Django 2.2.3 on 2019-07-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmp', '0007_auto_20190718_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')]),
        ),
    ]
