# Generated by Django 2.2.3 on 2019-07-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmp', '0008_auto_20190718_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')])),
                ('branch', models.CharField(blank=True, choices=[('A1', 'B.E. Chemical'), ('A2', 'B.E. Civil'), ('A7', 'B.E. Computer Science'), ('A3', 'B.E. Electrical & Electronics'), ('A8', 'B.E. Electronics & Instrumentation'), ('A4', 'B.E. Mechanical'), ('AB', 'B.E. Manufacturing'), ('A5', 'B.Pharm.'), ('B1', 'M.Sc. Biological Sciences'), ('B2', 'M.Sc. Chemistry'), ('B3', 'M.Sc. Economics'), ('B4', 'M.Sc. Mathematics'), ('B5', 'M.Sc. Physics')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_listed', models.BooleanField(default=True)),
                ('details', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('tags', models.CharField(max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='bookmp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='book_images')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookmp.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='bookmp.BookClass')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_instances', to='bookmp.Seller')),
            ],
        ),
        migrations.AddField(
            model_name='bookclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookmp.Course'),
        ),
    ]
