# Generated by Django 2.2.3 on 2019-07-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmp', '0010_auto_20190721_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='unique_code',
            field=models.CharField(default='lolmao', max_length=10),
        ),
    ]
