# Generated by Django 2.2.3 on 2019-07-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmp', '0012_course_is_elective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dual_branch',
            field=models.CharField(blank=True, choices=[('B1', 'M.Sc. Biological Sciences'), ('B2', 'M.Sc. Chemistry'), ('B3', 'M.Sc. Economics'), ('B4', 'M.Sc. Mathematics'), ('B5', 'M.Sc. Physics')], max_length=100, null=True),
        ),
    ]
