# Generated by Django 2.2.3 on 2019-07-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmp', '0013_auto_20190727_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='branch',
            field=models.CharField(blank=True, choices=[('ALL', 'All Branches'), ('A1', 'B.E. Chemical'), ('A2', 'B.E. Civil'), ('A7', 'B.E. Computer Science'), ('A3', 'B.E. Electrical & Electronics'), ('A8', 'B.E. Electronics & Instrumentation'), ('A4', 'B.E. Mechanical'), ('AB', 'B.E. Manufacturing'), ('A5', 'B.Pharm.'), ('B1', 'M.Sc. Biological Sciences'), ('B2', 'M.Sc. Chemistry'), ('B3', 'M.Sc. Economics'), ('B4', 'M.Sc. Mathematics'), ('B5', 'M.Sc. Physics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')], null=True),
        ),
    ]
