# Generated by Django 2.2.3 on 2019-07-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmp', '0015_auto_20190728_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_elective',
            new_name='is_humanities_elective',
        ),
        migrations.AddField(
            model_name='course',
            name='is_department_elective',
            field=models.BooleanField(default=False),
        ),
    ]
